server:
  port: 8081
  
spring:
  profiles: default
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        input:
          group: book
          destination: tanda
          contentType: application/json
        output:
          destination: tanda
          contentType: application/json
---
server:
  port: 8081
spring:
  profiles: aws
  cloud:
    stream:
      kafka:
        binder:
          brokers: 3.34.223.233:9092
      bindings:
        input:
          group: book
          destination: tanda
          contentType: application/json
        output:
          destination: tanda
          contentType: application/json

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      ddl-auto: update
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect:  org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://${_DATASOURCE_ADDRESS}/${_DATASOURCE_TABLESPACE}
    username: ${_DATASOURCE_USERNAME}
    password: ${_DATASOURCE_PASSWORD}   


---
server:
  port: 8081
  
spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.kafka.svc.cluster.local:9092
      bindings:
        input:
          group: book
          destination: tanda
          contentType: application/json
        output:
          destination: tanda
          contentType: application/json

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect:  org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://${_DATASOURCE_ADDRESS}/${_DATASOURCE_TABLESPACE}
    username: sa
    password: tanda2020
#    username: ${_DATASOURCE_USERNAME}
#    password: ${_DATASOURCE_PASSWORD}   
    
    
